AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ApplicationLoadBalancerArn:
    Type: String
    Description: "[REQUIRED] The arn of application load balancer like (app/<ALB NAME>/<RANDOM STR>)."
  RequestCountAnomalyAlarmName:
    Type: String
    Description: "[optional] The name of RequestCountAnomalyAlarm."
    Default: ""
  HTTPCodeTarget5XXCountAlarmName:
    Type: String
    Description: "[optional] The name of HTTPCode_Target_5XX_CountAlarm."
    Default: ""
  HTTPCodeELB5XXCountAlarmName:
    Type: String
    Description: "[optional] The name of HTTPCode_ELB_5XX_CountAlarm."
    Default: ""
  TargetResponseTimeAlarmName:
    Type: String
    Description: "[optional] The name of TargetResponseTimeAlarm."
    Default: ""
  TargetCountThreshold:
    Type: Number
    Description: "[optional] The number of HTTPCode_Target_5XX_Count and HTTPCode_ELB_5XX_Count threshold. Default is 100(count)."
    Default: '100'
  TargetResponseThreshold:
    Type: Number
    Description: "[optional] The number(doucle) of TargetResponseTime threshold. Default is 2.0(s)."
    Default: '2.0'

Conditions:
  UseRequestCountAnomalyAlarmName:
    !Not [!Equals [!Ref RequestCountAnomalyAlarmName, ""]]
  UseHTTPCodeTarget5XXCountAlarmName:
    !Not [!Equals [!Ref HTTPCodeTarget5XXCountAlarmName, ""]]
  UseHTTPCodeELB5XXCountAlarmName:
    !Not [!Equals [!Ref HTTPCodeELB5XXCountAlarmName, ""]]
  UseTargetResponseTimeAlarmName:
    !Not [!Equals [!Ref TargetResponseTimeAlarmName, ""]]

Resources:
  RequestCountAnomalyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmName: !If
        - UseRequestCountAnomalyAlarmName
        - !Ref RequestCountAnomalyAlarmName
        - !Sub
          - "ApplicationLoadBalancer/${AlbName}/RequestCountAnomaly"
          - AlbName: !Select
              - 1
              - !Split
                - "/"
                - !Ref ApplicationLoadBalancerArn
      ComparisonOperator: GreaterThanUpperThreshold
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Metrics:
        - Id: m1
          MetricStat:
            Metric:
              Namespace: AWS/ApplicationELB
              MetricName: RequestCount
              Dimensions:
                - Name: LoadBalancer
                  Value: !Ref ApplicationLoadBalancerArn
            Period: 60
            Stat: Sum
          ReturnData: true
        - Id: ad1
          Expression: "ANOMALY_DETECTION_BAND(m1, 2)"
          Label: RequestCount (expected)
          ReturnData: true
      ThresholdMetricId: ad1
      TreatMissingData: missing
  HTTPCodeTarget5XXCountAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmName: !If
        - UseHTTPCodeTarget5XXCountAlarmName
        - !Ref HTTPCodeTarget5XXCountAlarm
        - !Sub
          - "ApplicationLoadBalancer/${AlbName}/HTTPCodeTarget5XXCount"
          - AlbName: !Select
              - 1
              - !Split
                - "/"
                - !Ref ApplicationLoadBalancerArn
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref ApplicationLoadBalancerArn
      EvaluationPeriods: 1
      MetricName: HTTPCode_Target_5XX_Count
      Namespace: AWS/ApplicationELB 
      Period: 60
      Statistic: Sum
      Threshold: !Ref TargetCountThreshold
      TreatMissingData: missing
  HTTPCodeELB5XXCountAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmName: !If
        - UseHTTPCodeELB5XXCountAlarmName
        - !Ref HTTPCodeELB5XXCountAlarmName
        - !Sub
          - "ApplicationLoadBalancer/${AlbName}/HTTPCodeELB5XXCount"
          - AlbName: !Select
              - 1
              - !Split
                - "/"
                - !Ref ApplicationLoadBalancerArn
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref ApplicationLoadBalancerArn
      EvaluationPeriods: 1
      MetricName: HTTPCode_ELB_5XX_Count
      Namespace: AWS/ApplicationELB 
      Period: 60
      Statistic: Sum
      Threshold: !Ref TargetCountThreshold
      TreatMissingData: missing
  TargetResponseTimeAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmName: !If
        - UseTargetResponseTimeAlarmName
        - !Ref TargetResponseTimeAlarm
        - !Sub
          - "ApplicationLoadBalancer/${AlbName}/TargetResponseTime"
          - AlbName: !Select
              - 1
              - !Split
                - "/"
                - !Ref ApplicationLoadBalancerArn
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref ApplicationLoadBalancerArn
      EvaluationPeriods: 1
      MetricName: TargetResponseTime
      Namespace: AWS/ApplicationELB
      Period: 60
      Statistic: Average
      Threshold: !Ref TargetResponseThreshold
      TreatMissingData: missing

Outputs:
  AlamrsList:
    Value: !Join
      - ','
      - - !GetAtt RequestCountAnomalyAlarm.Arn
        - !GetAtt HTTPCodeTarget5XXCountAlarm.Arn
        - !GetAtt TargetResponseTimeAlarm.Arn
  RequestCountAnomalyAlarmArn:
    Value: !GetAtt RequestCountAnomalyAlarm.Arn
  HTTPCodeTarget5XXCountAlarmArn:
    Value: !GetAtt HTTPCodeTarget5XXCountAlarm.Arn
  HTTPCodeELB5XXCountAlarmArn:
    Value: !GetAtt HTTPCodeELB5XXCountAlarm.Arn
  TargetResponseTimeAlarmArn:
    Value: !GetAtt TargetResponseTimeAlarm.Arn